import ClientProvider from '@/components/ClientProvider';
import './globals.css';
import Header from '@/components/Header';

export const metadata = {
  title: '짧은 URL 만들기',
  description: 'Generated by min33sky',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`h-full overflow-hidden bg-gradient-to-br from-slate-500
                      to-slate-50 antialiased dark:from-slate-700`}
      >
        <ClientProvider>
          <Header />
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
